// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Generates the spec-derived half of the Token Standard registry server: a
 * typed routing table plus the `RegistryOperations`/`RegistryHandlers` types,
 * from the registry OpenAPI specifications.
 *
 * Only spec-specific data is generated. The reusable Express router runtime and
 * the shared type machinery are hand-written in
 * core/test-token-v1/src/registry/http/openapi-router.ts, which the generated
 * file imports. Implementers supply an `operationId -> handler` map that is
 * type-checked against the specs.
 */

import * as fs from 'fs'
import * as path from 'path'
import * as yaml from 'js-yaml'
import { getRepoRoot, SUPPORTED_VERSIONS, success, info } from './utils.js'
import type { Network } from './utils.js'

const HTTP_METHODS = ['get', 'post', 'put', 'delete', 'patch'] as const
type HttpMethod = (typeof HTTP_METHODS)[number]

interface Route {
    operationId: string
    method: HttpMethod
    path: string
}

/**
 * The registry OpenAPI specs, paired with the token-standard export name of the
 * `operations` type generated from each.
 */
const SPECS = [
    { file: 'token-metadata-v1.yaml', operations: 'metadataApiOperations' },
    {
        file: 'transfer-instruction-v1.yaml',
        operations: 'transferInstructionApiOperations',
    },
    {
        file: 'allocation-instruction-v1.yaml',
        operations: 'allocationInstructionApiOperations',
    },
    { file: 'allocation-v1.yaml', operations: 'allocationApiOperations' },
] as const

const OUTPUT =
    'core/test-token-v1/src/registry/generated-server/registry-server.ts'

interface OpenApiDoc {
    paths?: Record<
        string,
        Record<string, { operationId?: string } | undefined> | undefined
    >
}

/** Convert an OpenAPI path template (`/x/{id}`) to an Express path (`/x/:id`). */
function toExpressPath(openApiPath: string): string {
    return openApiPath.replace(/\{([^}]+)\}/g, ':$1')
}

function extractRoutes(doc: OpenApiDoc): Route[] {
    const routes: Route[] = []
    for (const [pathTemplate, item] of Object.entries(doc.paths ?? {})) {
        for (const method of HTTP_METHODS) {
            const operationId = item?.[method]?.operationId
            if (operationId)
                routes.push({
                    operationId,
                    method,
                    path: toExpressPath(pathTemplate),
                })
        }
    }
    return routes
}

function renderStub(routes: Route[], version: string): string {
    const year = new Date().getFullYear()
    const specList = SPECS.map(
        (s) => ` *   api-specs/splice/${version}/${s.file}`
    ).join('\n')
    const imports = SPECS.map((s) => `    ${s.operations},`).join('\n')
    const operationsUnion = SPECS.map((s) => s.operations).join(' &\n    ')
    const routeLines = routes
        .map(
            (r) =>
                `    { operationId: '${r.operationId}', method: '${r.method}', path: '${r.path}' },`
        )
        .join('\n')

    return `// Copyright (c) 2025-${year} Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * AUTO-GENERATED by scripts/src/lib/generate-registry-server.ts — DO NOT EDIT.
 *
 * Spec-derived routing table and operation types for the Token Standard
 * off-ledger registry APIs. The reusable Express router runtime is hand-written
 * in ../http/openapi-router.ts; only the data below is generated from the specs:
${specList}
 *
 * Regenerate with: yarn script:generate:openapi
 */

import type {
${imports}
} from '@canton-network/core-token-standard'
import type { OperationHandlers, Route } from '../http/openapi-router.js'

/** Every registry operation across the specs, keyed by \`operationId\`. */
export type RegistryOperations = ${operationsUnion}

/**
 * The complete registry handler map. Every \`operationId\` must be implemented,
 * with params/body/response types checked against the specs.
 */
export type RegistryHandlers = OperationHandlers<RegistryOperations>

/** Routing table (method + path per \`operationId\`) extracted from the specs. */
export const REGISTRY_ROUTES: readonly Route<RegistryOperations>[] = [
${routeLines}
]
`
}

/**
 * Generates the registry Express server stub from the local OpenAPI specs for
 * the Splice version configured for `network`. Reads specs from
 * `api-specs/splice/<version>/`; performs no network access.
 */
export async function generateRegistryServerStub(
    network: Network = 'devnet'
): Promise<void> {
    const root = getRepoRoot()
    const version = SUPPORTED_VERSIONS[network].splice.version
    const specDir = path.join(root, 'api-specs', 'splice', version)

    const routes: Route[] = []
    for (const { file } of SPECS) {
        const doc = yaml.load(
            fs.readFileSync(path.join(specDir, file), 'utf8')
        ) as OpenApiDoc
        routes.push(...extractRoutes(doc))
    }

    const outPath = path.join(root, OUTPUT)
    fs.mkdirSync(path.dirname(outPath), { recursive: true })
    fs.writeFileSync(outPath, renderStub(routes, version))

    console.log(
        success(
            `Generated registry Express server stub (${routes.length} routes): ${info(OUTPUT)}`
        )
    )
}
