// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import * as path from 'path'
import type { components } from '@open-rpc/generator'
import { execSync } from 'child_process'
import lodash from 'lodash'
import { validateOpenRpc } from './validate-openrpc.js'
const { template } = lodash

// Unknown keys are still rejected unless null (e.g. fields the Scan app returns as null).
const allowNullExtras = (value: unknown): unknown => {
    if (Array.isArray(value)) return value.map(allowNullExtras)
    if (typeof value !== 'object' || value === null) return value
    return Object.fromEntries(
        Object.entries(value).map(([key, sub]) => [
            key,
            key === 'additionalProperties' && sub === false
                ? { type: 'null' }
                : allowNullExtras(sub),
        ])
    )
}

// openrpcDocument still has cross-file $refs; methodTypings holds the dereferenced document.
const paramSchemasTemplate = template(
    `// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by rpc-generator DO NOT EDIT!!

import { z } from 'zod'

// Methods without a declared param only accept an omitted or empty \`params\`.
const noParams = z.union([z.undefined(), z.tuple([]), z.strictObject({})])

export const paramSchemas: Record<string, z.ZodType> = {
<% methodTypings.openrpcDocument.methods.forEach(({ name, params: [param] }) => { %>  <%= JSON.stringify(name) %>: <%= param ? 'z.fromJSONSchema(' + JSON.stringify(allowNullExtras(param.schema)) + ')' + (param.required ? '' : '.optional()') : 'noParams' %>,
<% }); %>}
`,
    { imports: { allowNullExtras } }
)

const hooks: components.IHooks = {
    beforeCompileTemplate: [validateOpenRpc],
    afterCompileTemplate: [
        async (dest): Promise<void> => {
            execSync(`pnpm eslint --fix ${dest}`)
            execSync(
                `pnpm prettier --write --no-error-on-unmatched-pattern ${dest}/**/*`
            )
        },
    ],
    templateFiles: {
        typescript: [
            {
                path: 'schemas.ts',
                template: paramSchemasTemplate,
            },
        ],
    },
}

// The generator CLI loads components via `(await import(path)).default`.
export default {
    hooks,
    staticPath: () =>
        path.join(import.meta.dirname, '../../templates/schemas/'),
}
