// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type { components } from '@open-rpc/generator'
import lodash from 'lodash'
import controller, { controllerTemplates } from './controller.js'
const { template } = lodash

// Unknown keys are still rejected unless null (e.g. fields the Scan app returns as null).
const allowNullExtras = (value: unknown): unknown => {
    if (Array.isArray(value)) return value.map(allowNullExtras)
    if (typeof value !== 'object' || value === null) return value
    return Object.fromEntries(
        Object.entries(value).map(([key, sub]) => [
            key,
            key === 'additionalProperties' && sub === false
                ? { type: 'null' }
                : allowNullExtras(sub),
        ])
    )
}

// Controller that also emits zod param validators; the target package must depend on zod.
// openrpcDocument still has cross-file $refs; methodTypings holds the dereferenced document.
const paramSchemasTemplate = template(
    `// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by rpc-generator DO NOT EDIT!!

import { z } from 'zod'

// Methods without a declared param only accept an omitted or empty \`params\`.
const noParams = z.union([z.undefined(), z.tuple([]), z.strictObject({})])

export const paramSchemas: Record<string, z.ZodType> = {
<% methodTypings.openrpcDocument.methods.forEach(({ name, params: [param] }) => { %>  <%= JSON.stringify(name) %>: <%= param ? 'z.fromJSONSchema(' + JSON.stringify(allowNullExtras(param.schema)) + ')' + (param.required ? '' : '.optional()') : 'noParams' %>,
<% }); %>}
`,
    { imports: { allowNullExtras } }
)

const hooks: components.IHooks = {
    ...controller.hooks,
    templateFiles: {
        typescript: [
            ...controllerTemplates,
            { path: 'schemas.ts', template: paramSchemasTemplate },
        ],
    },
}

// The generator CLI loads components via `(await import(path)).default`.
export default { hooks, staticPath: controller.staticPath }
