// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type * as openrpcgen from '@open-rpc/generator'
import lodash from 'lodash'
import { controllerTemplates, hooks as controllerHooks } from './controller'
const { template } = lodash

// Controller that also emits zod param validators; the target package must depend on zod.
// openrpcDocument still has cross-file $refs; methodTypings holds the dereferenced document.
const paramSchemasTemplate = template(
    `// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by rpc-generator DO NOT EDIT!!

import { z } from 'zod'

// Methods without a declared param only accept an omitted or empty \`params\`.
const noParams = z.union([z.undefined(), z.tuple([]), z.strictObject({})])

export const paramSchemas: Record<string, z.ZodType> = {
<% methodTypings.openrpcDocument.methods.forEach(({ name, params: [param] }) => { %>  <%= JSON.stringify(name) %>: <%= param ? 'z.fromJSONSchema(' + JSON.stringify(param.schema) + ')' + (param.required ? '' : '.optional()') : 'noParams' %>,
<% }); %>}
`
)

export const hooks: openrpcgen.components.IHooks = {
    ...controllerHooks,
    templateFiles: {
        typescript: [
            ...controllerTemplates,
            { path: 'schemas.ts', template: paramSchemasTemplate },
        ],
    },
}

export { staticPath } from './controller'
