enableScripts: true

npmMinimalAgeGate: 2880 # minimum age in minutes (48 hours)

npmRegistryServer: 'https://registry.npmjs.org'

nodeLinker: pnpm

packageExtensions:
    '@json-schema-tools/reference-resolver@*':
        dependencies:
            '@json-schema-tools/meta-schema': '*'
    '@open-rpc/generator@*':
        dependencies:
            '@inquirer/prompts': ^3.0.0
            '@open-rpc/schema-utils-js': ^2.0.2
    undici-types@*:
        dependencies:
            '@types/node': '*'
    vite-express@*:
        dependencies:
            vite: '*'
    vitest@*:
        dependencies:
            '@vitest/coverage-v8': '*'
