// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by rpc-generator DO NOT EDIT!!

import { z } from 'zod'

// Methods without a declared param only accept an omitted or empty `params`.
const noParams = z.union([z.undefined(), z.tuple([]), z.strictObject({})])

export const paramSchemas: Record<string, z.ZodType> = {
    addNetwork: z.fromJSONSchema({
        title: 'AddNetworkParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            network: {
                title: 'Network',
                type: 'object',
                additionalProperties: { type: 'null' },
                description: 'Structure representing the Networks',
                properties: {
                    id: {
                        title: 'networkId',
                        type: 'string',
                        description: 'Network ID',
                    },
                    name: {
                        title: 'name',
                        type: 'string',
                        description: 'Name of network',
                    },
                    description: {
                        title: 'description',
                        type: 'string',
                        description: 'Description of network',
                    },
                    synchronizerId: {
                        title: 'synchronizerId',
                        type: 'string',
                        description: 'Synchronizer ID',
                    },
                    identityProviderId: {
                        title: 'identityProviderId',
                        type: 'string',
                        description: 'Identity Provider ID',
                    },
                    auth: {
                        title: 'Auth',
                        description:
                            'Authentication configuration for a network',
                        oneOf: [
                            {
                                title: 'AuthorizationCodeAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Authorization code authentication configuration',
                                properties: {
                                    method: {
                                        title: 'authorizationCodeAuthMethod',
                                        type: 'string',
                                        enum: ['authorization_code'],
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    clientId: {
                                        title: 'clientId',
                                        type: 'string',
                                    },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Participant ID prefixed with "https://daml.com/jwt/aud/participant/".',
                                    },
                                },
                                required: [
                                    'method',
                                    'audience',
                                    'scope',
                                    'clientId',
                                ],
                            },
                            {
                                title: 'ClientCredentialsAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Client credentials authentication configuration',
                                properties: {
                                    method: {
                                        title: 'clientCredentialsAuthMethod',
                                        type: 'string',
                                        enum: ['client_credentials'],
                                    },
                                    identityProviderId: {
                                        title: 'clientCredentialsIdentityProviderId',
                                        type: 'string',
                                        description:
                                            "Overrides the network's identity provider for client credentials token acquisition",
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    clientId: {
                                        title: 'clientId',
                                        type: 'string',
                                    },
                                    clientSecret: {
                                        title: 'clientSecret',
                                        type: 'string',
                                    },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Participant ID prefixed with "https://daml.com/jwt/aud/participant/".',
                                    },
                                },
                                required: [
                                    'method',
                                    'audience',
                                    'scope',
                                    'clientId',
                                    'clientSecret',
                                ],
                            },
                            {
                                title: 'SelfSignedAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Self-signed authentication configuration',
                                properties: {
                                    method: {
                                        title: 'selfSignedAuthMethod',
                                        type: 'string',
                                        enum: ['self_signed'],
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    clientId: {
                                        title: 'clientId',
                                        type: 'string',
                                    },
                                    clientSecret: {
                                        title: 'clientSecret',
                                        type: 'string',
                                    },
                                    issuer: { title: 'issuer', type: 'string' },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Participant ID prefixed with "https://daml.com/jwt/aud/participant/".',
                                    },
                                },
                                required: [
                                    'method',
                                    'audience',
                                    'scope',
                                    'clientId',
                                    'clientSecret',
                                    'issuer',
                                ],
                            },
                            {
                                title: 'SelfIssuedAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Self-issued authentication configuration',
                                properties: {
                                    method: {
                                        title: 'selfIssuedAuthMethod',
                                        type: 'string',
                                        enum: ['self_issued'],
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Bare participant ID, with no https://daml.com/jwt/aud/participant/ prefix (unlike the other auth methods).',
                                    },
                                },
                                required: ['method', 'audience', 'scope'],
                            },
                        ],
                    },
                    adminAuth: {
                        title: 'Auth',
                        description:
                            'Authentication configuration for a network',
                        oneOf: [
                            {
                                title: 'AuthorizationCodeAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Authorization code authentication configuration',
                                properties: {
                                    method: {
                                        title: 'authorizationCodeAuthMethod',
                                        type: 'string',
                                        enum: ['authorization_code'],
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    clientId: {
                                        title: 'clientId',
                                        type: 'string',
                                    },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Participant ID prefixed with "https://daml.com/jwt/aud/participant/".',
                                    },
                                },
                                required: [
                                    'method',
                                    'audience',
                                    'scope',
                                    'clientId',
                                ],
                            },
                            {
                                title: 'ClientCredentialsAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Client credentials authentication configuration',
                                properties: {
                                    method: {
                                        title: 'clientCredentialsAuthMethod',
                                        type: 'string',
                                        enum: ['client_credentials'],
                                    },
                                    identityProviderId: {
                                        title: 'clientCredentialsIdentityProviderId',
                                        type: 'string',
                                        description:
                                            "Overrides the network's identity provider for client credentials token acquisition",
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    clientId: {
                                        title: 'clientId',
                                        type: 'string',
                                    },
                                    clientSecret: {
                                        title: 'clientSecret',
                                        type: 'string',
                                    },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Participant ID prefixed with "https://daml.com/jwt/aud/participant/".',
                                    },
                                },
                                required: [
                                    'method',
                                    'audience',
                                    'scope',
                                    'clientId',
                                    'clientSecret',
                                ],
                            },
                            {
                                title: 'SelfSignedAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Self-signed authentication configuration',
                                properties: {
                                    method: {
                                        title: 'selfSignedAuthMethod',
                                        type: 'string',
                                        enum: ['self_signed'],
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    clientId: {
                                        title: 'clientId',
                                        type: 'string',
                                    },
                                    clientSecret: {
                                        title: 'clientSecret',
                                        type: 'string',
                                    },
                                    issuer: { title: 'issuer', type: 'string' },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Participant ID prefixed with "https://daml.com/jwt/aud/participant/".',
                                    },
                                },
                                required: [
                                    'method',
                                    'audience',
                                    'scope',
                                    'clientId',
                                    'clientSecret',
                                    'issuer',
                                ],
                            },
                            {
                                title: 'SelfIssuedAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Self-issued authentication configuration',
                                properties: {
                                    method: {
                                        title: 'selfIssuedAuthMethod',
                                        type: 'string',
                                        enum: ['self_issued'],
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Bare participant ID, with no https://daml.com/jwt/aud/participant/ prefix (unlike the other auth methods).',
                                    },
                                },
                                required: ['method', 'audience', 'scope'],
                            },
                        ],
                    },
                    serviceAccountAuth: {
                        title: 'Auth',
                        description:
                            'Authentication configuration for a network',
                        oneOf: [
                            {
                                title: 'AuthorizationCodeAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Authorization code authentication configuration',
                                properties: {
                                    method: {
                                        title: 'authorizationCodeAuthMethod',
                                        type: 'string',
                                        enum: ['authorization_code'],
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    clientId: {
                                        title: 'clientId',
                                        type: 'string',
                                    },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Participant ID prefixed with "https://daml.com/jwt/aud/participant/".',
                                    },
                                },
                                required: [
                                    'method',
                                    'audience',
                                    'scope',
                                    'clientId',
                                ],
                            },
                            {
                                title: 'ClientCredentialsAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Client credentials authentication configuration',
                                properties: {
                                    method: {
                                        title: 'clientCredentialsAuthMethod',
                                        type: 'string',
                                        enum: ['client_credentials'],
                                    },
                                    identityProviderId: {
                                        title: 'clientCredentialsIdentityProviderId',
                                        type: 'string',
                                        description:
                                            "Overrides the network's identity provider for client credentials token acquisition",
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    clientId: {
                                        title: 'clientId',
                                        type: 'string',
                                    },
                                    clientSecret: {
                                        title: 'clientSecret',
                                        type: 'string',
                                    },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Participant ID prefixed with "https://daml.com/jwt/aud/participant/".',
                                    },
                                },
                                required: [
                                    'method',
                                    'audience',
                                    'scope',
                                    'clientId',
                                    'clientSecret',
                                ],
                            },
                            {
                                title: 'SelfSignedAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Self-signed authentication configuration',
                                properties: {
                                    method: {
                                        title: 'selfSignedAuthMethod',
                                        type: 'string',
                                        enum: ['self_signed'],
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    clientId: {
                                        title: 'clientId',
                                        type: 'string',
                                    },
                                    clientSecret: {
                                        title: 'clientSecret',
                                        type: 'string',
                                    },
                                    issuer: { title: 'issuer', type: 'string' },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Participant ID prefixed with "https://daml.com/jwt/aud/participant/".',
                                    },
                                },
                                required: [
                                    'method',
                                    'audience',
                                    'scope',
                                    'clientId',
                                    'clientSecret',
                                    'issuer',
                                ],
                            },
                            {
                                title: 'SelfIssuedAuth',
                                type: 'object',
                                additionalProperties: { type: 'null' },
                                description:
                                    'Self-issued authentication configuration',
                                properties: {
                                    method: {
                                        title: 'selfIssuedAuthMethod',
                                        type: 'string',
                                        enum: ['self_issued'],
                                    },
                                    scope: { title: 'scope', type: 'string' },
                                    audience: {
                                        title: 'audience',
                                        type: 'string',
                                        description:
                                            'Bare participant ID, with no https://daml.com/jwt/aud/participant/ prefix (unlike the other auth methods).',
                                    },
                                },
                                required: ['method', 'audience', 'scope'],
                            },
                        ],
                    },
                    ledgerApi: {
                        title: 'ledgerApi',
                        type: 'string',
                        description: 'Ledger api url',
                    },
                },
                required: [
                    'id',
                    'name',
                    'description',
                    'identityProviderId',
                    'auth',
                    'ledgerApi',
                ],
            },
        },
        required: ['network'],
    }),
    removeNetwork: z.fromJSONSchema({
        title: 'RemoveNetworkParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            networkName: {
                title: 'networkName',
                type: 'string',
                description: 'Ledger api url',
            },
        },
        required: ['networkName'],
    }),
    listNetworks: noParams,
    getNetwork: z.fromJSONSchema({
        title: 'GetNetworkParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            networkId: {
                title: 'networkId',
                type: 'string',
                description: 'Network ID',
            },
        },
        required: ['networkId'],
    }),
    selfSignedAccessToken: z.fromJSONSchema({
        title: 'SelfSignedAccessTokenParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            networkId: {
                title: 'networkId',
                type: 'string',
                description: 'Network ID',
            },
            clientId: {
                title: 'clientId',
                type: 'string',
                description: 'Client ID used as the JWT subject',
            },
            clientSecret: {
                title: 'clientSecret',
                type: 'string',
                description:
                    "Client secret that must match the selected network's auth.clientSecret",
            },
        },
        required: ['networkId', 'clientId', 'clientSecret'],
    }),
    addIdp: z.fromJSONSchema({
        title: 'AddIdpParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            idp: {
                title: 'Idp',
                description: 'Structure representing an identity provider',
                oneOf: [
                    {
                        title: 'OauthIdp',
                        type: 'object',
                        additionalProperties: { type: 'null' },
                        properties: {
                            id: {
                                title: 'id',
                                type: 'string',
                                description: 'ID of the identity provider',
                            },
                            type: {
                                title: 'oauthIdpType',
                                type: 'string',
                                enum: ['oauth'],
                                description: 'OAuth identity provider',
                            },
                            issuer: {
                                title: 'issuer',
                                type: 'string',
                                description: 'Issuer of identity provider',
                            },
                            configUrl: {
                                title: 'configUrl',
                                type: 'string',
                                description:
                                    'The configuration URL for the identity provider.',
                            },
                        },
                        required: ['id', 'type', 'issuer', 'configUrl'],
                    },
                    {
                        title: 'SelfSignedIdp',
                        type: 'object',
                        additionalProperties: { type: 'null' },
                        properties: {
                            id: {
                                title: 'id',
                                type: 'string',
                                description: 'ID of the identity provider',
                            },
                            type: {
                                title: 'selfSignedIdpType',
                                type: 'string',
                                enum: ['self_signed'],
                                description: 'Self-signed identity provider',
                            },
                            issuer: {
                                title: 'issuer',
                                type: 'string',
                                description: 'Issuer of identity provider',
                            },
                        },
                        required: ['id', 'type', 'issuer'],
                    },
                    {
                        title: 'SelfIssuedIdp',
                        type: 'object',
                        additionalProperties: { type: 'null' },
                        properties: {
                            id: {
                                title: 'id',
                                type: 'string',
                                description: 'ID of the identity provider',
                            },
                            type: {
                                title: 'selfIssuedIdpType',
                                type: 'string',
                                enum: ['self_issued'],
                                description: 'Self-issued identity provider',
                            },
                        },
                        required: ['id', 'type'],
                    },
                ],
            },
        },
        required: ['idp'],
    }),
    removeIdp: z.fromJSONSchema({
        title: 'RemoveIdpParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            identityProviderId: {
                title: 'identityProviderId',
                type: 'string',
                description: 'Identity Provider ID',
            },
        },
        required: ['identityProviderId'],
    }),
    listIdps: noParams,
    createWallet: z.fromJSONSchema({
        title: 'CreateWalletParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            primary: {
                title: 'primary',
                type: 'boolean',
                description: 'Set as primary wallet for dApp usage.',
            },
            partyHint: {
                title: 'partyHint',
                type: 'string',
                description: 'The party hint and name of the wallet.',
            },
            signingProviderId: {
                title: 'signingProviderId',
                type: 'string',
                description:
                    'The signing provider ID the wallet corresponds to.',
            },
            keyName: {
                title: 'keyName',
                type: 'string',
                description:
                    "Name of signing provider's key to use for getting keys.",
            },
        },
        required: ['partyHint', 'signingProviderId'],
    }),
    addSelfIssuedSession: z.fromJSONSchema({
        title: 'AddSelfIssuedSessionParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            username: {
                title: 'username',
                type: 'string',
                description: 'User id used while onboarding.',
            },
            networkId: {
                title: 'networkId',
                type: 'string',
                description: 'Self-issued network to onboard on.',
            },
            origin: {
                title: 'origin',
                type: 'string',
                description: 'Origin starting the onboarding flow.',
            },
        },
        required: ['username', 'networkId', 'origin'],
    }),
    getSelfIssuedOnboarding: z.fromJSONSchema({
        title: 'GetSelfIssuedOnboardingParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            sessionId: {
                title: 'sessionId',
                type: 'string',
                description:
                    'Onboarding session id returned by addSelfIssuedSession.',
            },
        },
        required: ['sessionId'],
    }),
    createSelfIssuedWallet: z.fromJSONSchema({
        title: 'CreateSelfIssuedWalletParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            sessionId: {
                title: 'sessionId',
                type: 'string',
                description:
                    'Onboarding session id returned by addSelfIssuedSession.',
            },
            partyHint: {
                title: 'partyHint',
                type: 'string',
                description: 'The party hint and name of the wallet.',
            },
            signingProviderId: {
                title: 'signingProviderId',
                type: 'string',
                description:
                    'Signing provider used to hold keys of the authentication party.',
            },
        },
        required: ['sessionId', 'partyHint', 'signingProviderId'],
    }),
    allocateSelfIssuedWallet: z.fromJSONSchema({
        title: 'AllocateSelfIssuedWalletParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            sessionId: {
                title: 'sessionId',
                type: 'string',
                description:
                    'Onboarding session id returned by addSelfIssuedSession.',
            },
            partyId: {
                title: 'partyId',
                type: 'string',
                description: 'Party id of the wallet awaiting allocation.',
            },
        },
        required: ['sessionId', 'partyId'],
    }),
    connectSelfIssuedSession: z.fromJSONSchema({
        title: 'ConnectSelfIssuedSessionParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            sessionId: {
                title: 'sessionId',
                type: 'string',
                description:
                    'Onboarding session id returned by addSelfIssuedSession.',
            },
            partyId: {
                title: 'partyId',
                type: 'string',
                description: 'Allocated party selected for authentication.',
            },
        },
        required: ['sessionId', 'partyId'],
    }),
    allocatePartyForWallet: z.fromJSONSchema({
        title: 'AllocatePartyForWalletParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            partyId: {
                title: 'partyId',
                type: 'string',
                description:
                    'The party ID of the initialized wallet to allocate.',
            },
        },
        required: ['partyId'],
    }),
    setPrimaryWallet: z.fromJSONSchema({
        title: 'SetPrimaryWalletParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            partyId: {
                title: 'partyId',
                type: 'string',
                description: 'The party id of the wallet to set as primary.',
            },
        },
        required: ['partyId'],
    }),
    removeWallet: z.fromJSONSchema({
        title: 'RemoveWalletParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            partyId: {
                title: 'partyId',
                type: 'string',
                description: 'The party id of the wallet to be removed.',
            },
        },
        required: ['partyId'],
    }),
    listWallets: z.fromJSONSchema({
        title: 'ListWalletsParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            filter: {
                title: 'WalletFilter',
                type: 'object',
                description: 'Filter for the wallets to be returned.',
                additionalProperties: { type: 'null' },
                properties: {
                    networkIds: {
                        title: 'networkIds',
                        type: 'array',
                        description: 'Filter wallets by network IDs.',
                        items: { title: 'networkId', type: 'string' },
                    },
                    signingProviderIds: {
                        title: 'signingProviderIds',
                        type: 'array',
                        description: 'Filter wallets by signing provider IDs.',
                        items: { title: 'signingProviderId', type: 'string' },
                    },
                },
            },
        },
        required: [],
    }),
    syncWallets: noParams,
    isWalletSyncNeeded: noParams,
    sign: z.fromJSONSchema({
        title: 'SignParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            transactionId: {
                title: 'transactionId',
                type: 'string',
                format: 'uuid',
                description: 'The internal transaction identifier.',
            },
            partyId: { title: 'partyId', type: 'string' },
        },
        required: ['transactionId', 'partyId'],
    }),
    signMessage: z.fromJSONSchema({
        title: 'SignMessageParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            messageId: {
                title: 'MessageId',
                type: 'string',
                format: 'uuid',
                description:
                    'The internal identifier of the pending message-signing request.',
            },
            partyId: {
                title: 'partyId',
                type: 'string',
                description:
                    'Party that should sign the message. If omitted, the primary wallet is used.',
            },
        },
        required: ['messageId'],
    }),
    getMessageToSign: z.fromJSONSchema({
        title: 'GetMessageToSignParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            messageId: {
                title: 'MessageId',
                type: 'string',
                format: 'uuid',
                description:
                    'The internal identifier of the pending message-signing request.',
            },
        },
        required: ['messageId'],
    }),
    listMessagesToSign: noParams,
    deleteMessageToSign: z.fromJSONSchema({
        title: 'DeleteMessageToSignParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            messageId: {
                title: 'MessageId',
                type: 'string',
                format: 'uuid',
                description:
                    'The internal identifier of the pending message-signing request.',
            },
        },
        required: ['messageId'],
    }),
    execute: z.fromJSONSchema({
        title: 'ExecuteParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            partyId: { title: 'partyId', type: 'string' },
            transactionId: {
                title: 'transactionId',
                type: 'string',
                format: 'uuid',
                description: 'The internal transaction identifier.',
            },
        },
        required: ['transactionId', 'partyId'],
    }),
    addSession: z.fromJSONSchema({
        title: 'AddSessionParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            origin: {
                title: 'origin',
                type: 'string',
                description: 'origin of the dApp establishing a session',
            },
            networkId: {
                title: 'networkId',
                type: 'string',
                description: 'Network Id',
            },
        },
        required: ['networkId', 'origin'],
    }),
    removeSession: noParams,
    listSessions: noParams,
    getTransaction: z.fromJSONSchema({
        title: 'GetTransactionParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            transactionId: {
                title: 'transactionId',
                type: 'string',
                format: 'uuid',
                description: 'The internal transaction identifier.',
            },
        },
        required: ['transactionId'],
    }),
    getTransactionStatus: z.fromJSONSchema({
        title: 'GetTransactionStatusParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            transactionId: {
                title: 'transactionId',
                type: 'string',
                format: 'uuid',
                description: 'The internal transaction identifier.',
            },
            partyId: {
                title: 'partyId',
                type: 'string',
                description: 'The party ID corresponding to the wallet.',
            },
        },
        required: ['transactionId'],
    }),
    listTransactions: z.fromJSONSchema({
        title: 'ListTransactionsParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            limit: {
                title: 'limit',
                type: 'integer',
                description: 'Limit of transactions to return.',
            },
            cursor: {
                title: 'cursor',
                type: ['string'],
                description: 'Cursor for next page of results.',
            },
        },
    }),
    deleteTransaction: z.fromJSONSchema({
        title: 'DeleteTransactionParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            transactionId: {
                title: 'transactionId',
                type: 'string',
                format: 'uuid',
                description: 'The internal transaction identifier.',
            },
        },
        required: ['transactionId'],
    }),
    getUser: noParams,
    generateApiKey: z.fromJSONSchema({
        title: 'GenerateApiKeyParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            name: {
                title: 'name',
                type: 'string',
                description: 'A name to identify the API key.',
            },
        },
        required: ['name'],
    }),
    listApiKeys: noParams,
    removeApiKey: z.fromJSONSchema({
        title: 'RemoveApiKeyParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            id: {
                title: 'id',
                type: 'string',
                description: 'The unique identifier of the API key.',
            },
        },
        required: ['id'],
    }),
    listSigningProviderKeys: z.fromJSONSchema({
        title: 'ListSigningProviderKeysParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            signingProviderId: {
                title: 'signingProviderId',
                type: 'string',
                description:
                    'The signing provider ID the wallet corresponds to.',
            },
        },
        required: ['signingProviderId'],
    }),
    getWallet: z.fromJSONSchema({
        title: 'GetWalletParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            partyId: {
                title: 'partyId',
                type: 'string',
                description: 'The party ID corresponding to the wallet.',
            },
        },
        required: ['partyId'],
    }),
    changeSigningProvider: z.fromJSONSchema({
        title: 'changeSigningProviderParams',
        type: 'object',
        additionalProperties: { type: 'null' },
        properties: {
            signingProviderId: {
                title: 'signingProviderId',
                type: 'string',
                description:
                    'The signing provider ID the party should correspond to.',
            },
            partyId: {
                title: 'partyId',
                type: 'string',
                description: 'The party ID corresponding to the wallet.',
            },
            publicKey: {
                title: 'publicKey',
                type: 'string',
                description:
                    "The key to be used for the party's signing provider",
            },
        },
        required: ['signingProviderId', 'partyId', 'publicKey'],
    }),
}
