// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * AUTO-GENERATED by scripts/src/lib/generate-registry-server.ts — DO NOT EDIT.
 *
 * Spec-derived routing table and operation types for the Token Standard
 * off-ledger registry APIs. The reusable Express router runtime is hand-written
 * in ../http/openapi-router.ts; only the data below is generated from the specs:
 *   api-specs/splice/0.6.1/token-metadata-v1.yaml
 *   api-specs/splice/0.6.1/transfer-instruction-v1.yaml
 *   api-specs/splice/0.6.1/allocation-instruction-v1.yaml
 *   api-specs/splice/0.6.1/allocation-v1.yaml
 *
 * Regenerate with: yarn script:generate:openapi
 */

import type {
    metadataApiOperations,
    transferInstructionApiOperations,
    allocationInstructionApiOperations,
    allocationApiOperations,
} from '@canton-network/core-token-standard'
import type { OperationHandlers, Route } from '../http/openapi-router.js'

/** Every registry operation across the specs, keyed by `operationId`. */
export type RegistryOperations = metadataApiOperations &
    transferInstructionApiOperations &
    allocationInstructionApiOperations &
    allocationApiOperations

/**
 * The complete registry handler map. Every `operationId` must be implemented,
 * with params/body/response types checked against the specs.
 */
export type RegistryHandlers = OperationHandlers<RegistryOperations>

/** Routing table (method + path per `operationId`) extracted from the specs. */
export const REGISTRY_ROUTES: readonly Route<RegistryOperations>[] = [
    {
        operationId: 'getRegistryInfo',
        method: 'get',
        path: '/registry/metadata/v1/info',
    },
    {
        operationId: 'listInstruments',
        method: 'get',
        path: '/registry/metadata/v1/instruments',
    },
    {
        operationId: 'getInstrument',
        method: 'get',
        path: '/registry/metadata/v1/instruments/:instrumentId',
    },
    {
        operationId: 'getTransferFactory',
        method: 'post',
        path: '/registry/transfer-instruction/v1/transfer-factory',
    },
    {
        operationId: 'getTransferInstructionAcceptContext',
        method: 'post',
        path: '/registry/transfer-instruction/v1/:transferInstructionId/choice-contexts/accept',
    },
    {
        operationId: 'getTransferInstructionRejectContext',
        method: 'post',
        path: '/registry/transfer-instruction/v1/:transferInstructionId/choice-contexts/reject',
    },
    {
        operationId: 'getTransferInstructionWithdrawContext',
        method: 'post',
        path: '/registry/transfer-instruction/v1/:transferInstructionId/choice-contexts/withdraw',
    },
    {
        operationId: 'getAllocationFactory',
        method: 'post',
        path: '/registry/allocation-instruction/v1/allocation-factory',
    },
    {
        operationId: 'getAllocationTransferContext',
        method: 'post',
        path: '/registry/allocations/v1/:allocationId/choice-contexts/execute-transfer',
    },
    {
        operationId: 'getAllocationWithdrawContext',
        method: 'post',
        path: '/registry/allocations/v1/:allocationId/choice-contexts/withdraw',
    },
    {
        operationId: 'getAllocationCancelContext',
        method: 'post',
        path: '/registry/allocations/v1/:allocationId/choice-contexts/cancel',
    },
]
