// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by rpc-generator DO NOT EDIT!!

import { z } from 'zod'

// Methods without a declared param only accept an omitted or empty `params`.
const noParams = z.union([z.undefined(), z.tuple([]), z.strictObject({})])

export const paramSchemas: Record<string, z.ZodType> = {
    status: noParams,
    connect: noParams,
    disconnect: noParams,
    isConnected: noParams,
    getActiveNetwork: noParams,
    prepareExecute: z.fromJSONSchema({
        title: 'prepareExecuteParams',
        type: 'object',
        description:
            'Structure representing the request for prepare and execute calls',
        additionalProperties: false,
        properties: {
            commandId: {
                title: 'CommandId',
                type: 'string',
                description:
                    'The unique identifier of the command associated with the transaction.',
            },
            commands: {
                title: 'Commands',
                type: 'array',
                minItems: 1,
                description:
                    'Non-empty array of Daml command atoms to submit atomically as a single transaction.',
                items: {
                    title: 'Command',
                    description:
                        'A Daml command atom. Mirror of the Canton Ledger API Command union; inner shapes are intentionally opaque so the dApp layer never drifts from the Ledger API contract.',
                    oneOf: [
                        {
                            title: 'CreateCommand',
                            type: 'object',
                            additionalProperties: false,
                            required: ['CreateCommand'],
                            properties: {
                                CreateCommand: {
                                    title: 'CreateCommandPayload',
                                    type: 'object',
                                    additionalProperties: true,
                                    description:
                                        'Inner shape is defined by the Canton Ledger API CreateCommand schema; do not re-specify here.',
                                },
                            },
                        },
                        {
                            title: 'ExerciseCommand',
                            type: 'object',
                            additionalProperties: false,
                            required: ['ExerciseCommand'],
                            properties: {
                                ExerciseCommand: {
                                    title: 'ExerciseCommandPayload',
                                    type: 'object',
                                    additionalProperties: true,
                                    description:
                                        'Inner shape is defined by the Canton Ledger API ExerciseCommand schema; do not re-specify here.',
                                },
                            },
                        },
                        {
                            title: 'CreateAndExerciseCommand',
                            type: 'object',
                            additionalProperties: false,
                            required: ['CreateAndExerciseCommand'],
                            properties: {
                                CreateAndExerciseCommand: {
                                    title: 'CreateAndExerciseCommandPayload',
                                    type: 'object',
                                    additionalProperties: true,
                                    description:
                                        'Inner shape is defined by the Canton Ledger API CreateAndExerciseCommand schema; do not re-specify here.',
                                },
                            },
                        },
                        {
                            title: 'ExerciseByKeyCommand',
                            type: 'object',
                            additionalProperties: false,
                            required: ['ExerciseByKeyCommand'],
                            properties: {
                                ExerciseByKeyCommand: {
                                    title: 'ExerciseByKeyCommandPayload',
                                    type: 'object',
                                    additionalProperties: true,
                                    description:
                                        'Inner shape is defined by the Canton Ledger API ExerciseByKeyCommand schema; do not re-specify here.',
                                },
                            },
                        },
                    ],
                },
            },
            actAs: {
                title: 'actAs',
                type: 'array',
                description:
                    "Set of parties on whose behalf the command should be executed, if submitted. If not set, the primary wallet's party is used.",
                items: { title: 'party', type: 'string' },
            },
            readAs: {
                title: 'readAs',
                type: 'array',
                description:
                    'Set of parties that should be granted read access to the command, if submitted. If not set, no additional read parties are granted.',
                items: { title: 'party', type: 'string' },
            },
            disclosedContracts: {
                title: 'disclosedContracts',
                type: 'array',
                description:
                    'List of contract IDs to be disclosed with the command.',
                items: {
                    title: 'DisclosedContract',
                    type: 'object',
                    description:
                        'Structure representing a disclosed contract for transaction execution',
                    additionalProperties: false,
                    properties: {
                        templateId: {
                            title: 'templateId',
                            type: 'string',
                            description:
                                'The template identifier of the disclosed contract.',
                        },
                        contractId: {
                            title: 'contractId',
                            type: 'string',
                            description:
                                'The unique identifier of the disclosed contract.',
                        },
                        createdEventBlob: {
                            title: 'createdEventBlob',
                            type: 'string',
                            description:
                                'The blob data of the created event for the disclosed contract.',
                        },
                        synchronizerId: {
                            title: 'synchronizerId',
                            type: 'string',
                            description:
                                'The synchronizer identifier associated with the disclosed contract.',
                        },
                    },
                    required: ['createdEventBlob'],
                },
            },
            synchronizerId: {
                title: 'synchronizerId',
                type: 'string',
                description:
                    'If not set, a suitable synchronizer that this node is connected to will be chosen.',
            },
            packageIdSelectionPreference: {
                title: 'packageIdSelectionPreference',
                type: 'array',
                description:
                    'The package-id selection preference of the client for resolving package names and interface instances in command submission and interpretation',
                items: { title: 'packageId', type: 'string' },
            },
        },
        required: ['commands'],
    }),
    signMessage: z.fromJSONSchema({
        title: 'signMessageParams',
        type: 'object',
        description: 'Request to sign a message.',
        additionalProperties: false,
        properties: {
            message: {
                title: 'message',
                type: 'string',
                description: 'The message to sign.',
            },
        },
        required: ['message'],
    }),
    ledgerApi: z.fromJSONSchema({
        title: 'ledgerApiParams',
        type: 'object',
        description: 'Ledger API request structure',
        additionalProperties: false,
        properties: {
            requestMethod: {
                title: 'requestMethod',
                type: 'string',
                enum: ['get', 'post', 'patch', 'put', 'delete'],
            },
            resource: { title: 'resource', type: 'string' },
            body: { title: 'body', type: 'object', additionalProperties: true },
            query: {
                title: 'query',
                type: 'object',
                additionalProperties: true,
                description: 'Query parameters as key-value pairs.',
            },
            path: {
                title: 'path',
                type: 'object',
                additionalProperties: true,
                description: 'Path parameters as key-value pairs.',
            },
        },
        required: ['requestMethod', 'resource'],
    }),
    connected: noParams,
    onStatusChanged: noParams,
    accountsChanged: noParams,
    getPrimaryAccount: noParams,
    listAccounts: noParams,
    txChanged: noParams,
    messageSignature: noParams,
}
