// Code generated by @open-rpc/generator DO NOT EDIT.
import _ from 'lodash'

import type { RequestArgs, RequestPayload } from '@canton-network/core-types'
import type { RpcTransport } from '@canton-network/core-rpc-transport'

/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 *
 * The network ID the wallet corresponds to.
 *
 */
export type NetworkId = string
export type Name = string
/**
 *
 * Description of network
 *
 */
export type Description = string
/**
 *
 * Synchronizer ID
 *
 */
export type SynchronizerId = string
/**
 *
 * Identity Provider ID
 *
 */
export type IdentityProviderId = string
export type AuthorizationCodeAuthMethod = 'authorization_code'
export type Scope = string
export type ClientId = string
/**
 *
 * Participant ID. Unlike other auth methods without a prefix "https://daml.com/jwt/aud/participant/".
 *
 */
export type Audience = string
/**
 *
 * Authorization code authentication configuration
 *
 */
export interface AuthorizationCodeAuth {
    method: AuthorizationCodeAuthMethod
    scope: Scope
    clientId: ClientId
    audience: Audience
}
export type ClientCredentialsAuthMethod = 'client_credentials'
/**
 *
 * Overrides the network's identity provider for client credentials token acquisition
 *
 */
export type ClientCredentialsIdentityProviderId = string
export type ClientSecret = string
/**
 *
 * Client credentials authentication configuration
 *
 */
export interface ClientCredentialsAuth {
    method: ClientCredentialsAuthMethod
    identityProviderId?: ClientCredentialsIdentityProviderId
    scope: Scope
    clientId: ClientId
    clientSecret: ClientSecret
    audience: Audience
}
export type SelfSignedAuthMethod = 'self_signed'
/**
 *
 * Issuer of identity provider
 *
 */
export type Issuer = string
/**
 *
 * Self-signed authentication configuration
 *
 */
export interface SelfSignedAuth {
    method: SelfSignedAuthMethod
    scope: Scope
    clientId: ClientId
    clientSecret: ClientSecret
    issuer: Issuer
    audience: Audience
}
export type SelfIssuedAuthMethod = 'self_issued'
/**
 *
 * Self-issued authentication configuration
 *
 */
export interface SelfIssuedAuth {
    method: SelfIssuedAuthMethod
    scope: Scope
    audience: Audience
}
/**
 *
 * Authentication configuration for a network
 *
 */
export type Auth =
    | AuthorizationCodeAuth
    | ClientCredentialsAuth
    | SelfSignedAuth
    | SelfIssuedAuth
/**
 *
 * Ledger api url
 *
 */
export type LedgerApi = string
/**
 *
 * Connected network metadata. Privileged credentials (adminAuth, serviceAccountAuth) are included only for the admin user.
 *
 */
export interface Network {
    id: NetworkId
    name: Name
    description: Description
    synchronizerId?: SynchronizerId
    identityProviderId: IdentityProviderId
    auth: Auth
    adminAuth?: Auth
    serviceAccountAuth?: Auth
    ledgerApi: LedgerApi
}
/**
 *
 * Ledger api url
 *
 */
export type NetworkName = string
export type Id = string
/**
 *
 * OAuth identity provider
 *
 */
export type OauthIdpType = 'oauth'
/**
 *
 * The configuration URL for the identity provider.
 *
 */
export type ConfigUrl = string
export interface OauthIdp {
    id: Id
    type: OauthIdpType
    issuer: Issuer
    configUrl: ConfigUrl
}
/**
 *
 * Self-signed identity provider
 *
 */
export type SelfSignedIdpType = 'self_signed'
export interface SelfSignedIdp {
    id: Id
    type: SelfSignedIdpType
    issuer: Issuer
}
/**
 *
 * Self-issued identity provider
 *
 */
export type SelfIssuedIdpType = 'self_issued'
export interface SelfIssuedIdp {
    id: Id
    type: SelfIssuedIdpType
}
/**
 *
 * Structure representing an identity provider
 *
 */
export type Idp = OauthIdp | SelfSignedIdp | SelfIssuedIdp
/**
 *
 * Set as primary wallet for dApp usage.
 *
 */
export type Primary = boolean
/**
 *
 * The party hint and name of the wallet.
 *
 */
export type PartyHint = string
/**
 *
 * The signing provider ID the wallet corresponds to.
 *
 */
export type SigningProviderId = string
/**
 *
 * Name of signing provider's key to use for getting keys.
 *
 */
export type KeyName = string
/**
 *
 * User id used while onboarding.
 *
 */
export type Username = string
/**
 *
 * The origin (dApp URL) that initiated this transaction request.
 *
 */
export type Origin = string
/**
 *
 * Onboarding session id required by the remaining self-issued onboarding methods.
 *
 */
export type SessionId = string
/**
 *
 * The party ID corresponding to the wallet.
 *
 */
export type PartyId = string
/**
 *
 * Filter wallets by network IDs.
 *
 */
export type NetworkIds = NetworkId[]
/**
 *
 * Filter wallets by signing provider IDs.
 *
 */
export type SigningProviderIds = SigningProviderId[]
/**
 *
 * Filter for the wallets to be returned.
 *
 */
export interface WalletFilter {
    networkIds?: NetworkIds
    signingProviderIds?: SigningProviderIds
}
/**
 *
 * The internal transaction identifier.
 *
 */
export type TransactionId = string
/**
 *
 * The internal identifier of the pending message-signing request.
 *
 */
export type MessageId = string
/**
 *
 * Limit of transactions to return.
 *
 */
export type Limit = number
/**
 *
 * Cursor for next page of results.
 *
 */
export type CursorAsString = string
/**
 *
 * Cursor for next page of results.
 *
 */
export type Cursor = CursorAsString
/**
 *
 * The public key of the party.
 *
 */
export type PublicKey = string
/**
 *
 * Authentication method configured for this network
 *
 */
export type AuthMethod = string
/**
 *
 * Network metadata exposed by listNetworks without sensitive auth configuration
 *
 */
export interface PublicNetwork {
    id: NetworkId
    name: Name
    description: Description
    synchronizerId?: SynchronizerId
    identityProviderId: IdentityProviderId
    ledgerApi: LedgerApi
    authMethod: AuthMethod
    clientId?: ClientId
    scope?: Scope
    audience?: Audience
}
export type Networks = PublicNetwork[]
/**
 *
 * The access token for the session.
 *
 */
export type AccessToken = string
export type Idps = Idp[]
/**
 *
 * The status of the wallet.
 *
 */
export type WalletStatus = 'initialized' | 'allocated' | 'removed'
/**
 *
 * The party hint and name of the wallet.
 *
 */
export type Hint = string
/**
 *
 * The namespace of the party.
 *
 */
export type Namespace = string
/**
 *
 * Unique identifier of the signed transaction given by the Signing Provider. This may not be the same as the internal txId given by the Wallet Gateway.
 *
 */
export type ExternalTxId = string
/**
 *
 * The topology transactions
 *
 */
export type TopologyTransactions = string
/**
 *
 * Whether the wallet is disabled. Wallets are disabled when no signing provider matches the party's namespace during sync. Disabled wallets use participant as the default signing provider.
 *
 */
export type Disabled = boolean
/**
 *
 * Reason for the wallet state, e.g., 'no signing provider matched'.
 *
 */
export type Reason = string
export type PartyLevelRight = any
/**
 *
 * The rights of the wallet.
 *
 */
export type Rights = PartyLevelRight[]
/**
 *
 * Structure representing a wallet
 *
 */
export interface Wallet {
    primary: Primary
    partyId: PartyId
    status: WalletStatus
    hint: Hint
    publicKey: PublicKey
    namespace: Namespace
    networkId: NetworkId
    signingProviderId: SigningProviderId
    externalTxId?: ExternalTxId
    topologyTransactions?: TopologyTransactions
    disabled?: Disabled
    reason?: Reason
    rights: Rights
}
/**
 *
 * Whether the ledger user already exists.
 *
 */
export type UserExists = boolean
/**
 *
 * Wallets stored for the user on the selected network.
 *
 */
export type Wallets = Wallet[]
type AlwaysTrue = any
/**
 *
 * Non-disabled wallets added in this syncWallets call.
 *
 */
export type SyncWalletsResultAdded = Wallet[]
/**
 *
 * Existing wallets that either got downgraded to status initialized or their rights changed in this syncWallets call.
 *
 */
export type SyncWalletsResultUpdated = Wallet[]
/**
 *
 * Either wallets added in this iteration that are disabled, or existing wallet that were updated to be disabled in this syncWallets call.
 *
 */
export type SyncWalletsResultDisabled = Wallet[]
/**
 *
 * Whether wallet sync is needed. Returns true if there are disabled wallets or parties on the ledger that aren't in the store.
 *
 */
export type WalletSyncNeeded = boolean
export type TxStatusSigned = 'signed'
/**
 *
 * The signature of the message.
 *
 */
export type Signature = string
export type SignedBy = string
export interface SignResultSigned {
    status: TxStatusSigned
    signature: Signature
    signedBy: SignedBy
    partyId: PartyId
    externalTxId?: ExternalTxId
}
export type TxStatusPending = 'pending'
export interface SignResultPending {
    status: TxStatusPending
    partyId: PartyId
    externalTxId: ExternalTxId
}
export type TxStatusRejected = 'rejected'
export interface SignResultRejected {
    status: TxStatusRejected
    partyId: PartyId
    externalTxId: ExternalTxId
}
export type TxStatusFailed = 'failed'
export interface SignResultFailed {
    status: TxStatusFailed
    partyId: PartyId
    externalTxId: ExternalTxId
}
/**
 *
 * The status of the transaction.
 *
 */
export type Status = string
/**
 *
 * The message to sign.
 *
 */
export type Message = string
/**
 *
 * The timestamp when the API key was created.
 *
 */
export type CreatedAt = string
/**
 *
 * The timestamp when the transaction was signed.
 *
 */
export type SignedAt = string
export interface MessageRaw {
    id: MessageId
    status: Status
    partyId: PartyId
    publicKey: PublicKey
    message: Message
    origin?: Origin
    createdAt: CreatedAt
    signedAt?: SignedAt
    signature?: Signature
}
export type Messages = MessageRaw[]
export type UserLevelRight = any
/**
 *
 * Structure representing the connected network session
 *
 */
export interface Session {
    id: Id
    origin?: Origin
    network: Network
    idp: Idp
    accessToken: AccessToken
    status: Status
    reason?: Reason
    rights: Rights
}
export type Sessions = Session[]
/**
 *
 * The unique identifier of the command associated with the transaction.
 *
 */
export type CommandId = string
/**
 *
 * The transaction data corresponding to the command ID.
 *
 */
export type PreparedTransaction = string
/**
 *
 * The hash of the prepared transaction.
 *
 */
export type PreparedTransactionHash = string
/**
 *
 * Optional payload associated with the transaction.
 *
 */
export type Payload = string
/**
 *
 * Reason for why the transaction failed.
 *
 */
export type FailureReason = string
export interface Transaction {
    id: TransactionId
    commandId: CommandId
    status: Status
    createdAt?: CreatedAt
    signedAt?: SignedAt
    preparedTransaction: PreparedTransaction
    preparedTransactionHash: PreparedTransactionHash
    payload?: Payload
    origin?: Origin
    externalTxId?: ExternalTxId
    failureReason?: FailureReason
}
export type Transactions = Transaction[]
/**
 *
 * Cursor for next page of results.
 *
 */
export type NextCursor = string
/**
 *
 * Number of total transactions for the user.
 *
 */
export type Count = number
/**
 *
 * The unique identifier of the current user.
 *
 */
export type UserIdentifier = string
/**
 *
 * Whether the current user is an admin.
 *
 */
export type IsAdminFlag = boolean
/**
 *
 * The generated API key.
 *
 */
export type ApiKeyResult = string
export interface ApiKey {
    id: Id
    name: Name
    createdAt: CreatedAt
}
/**
 *
 * The list of API keys.
 *
 */
export type ApiKeys = ApiKey[]
export interface Key {
    id: Id
    name: Name
    publicKey: PublicKey
}
/**
 *
 * The list of signing provider's available keys.
 *
 */
export type Keys = Key[]
/**
 *
 * Represents a null value, used in responses where no data is returned.
 *
 */
export type Null = null
export interface AddNetworkParams {
    network: Network
}
export interface RemoveNetworkParams {
    networkName: NetworkName
}
export interface GetNetworkParams {
    networkId: NetworkId
}
export interface SelfSignedAccessTokenParams {
    networkId: NetworkId
    clientId: ClientId
    clientSecret: ClientSecret
}
export interface AddIdpParams {
    idp: Idp
}
export interface RemoveIdpParams {
    identityProviderId: IdentityProviderId
}
export interface CreateWalletParams {
    primary?: Primary
    partyHint: PartyHint
    signingProviderId: SigningProviderId
    keyName?: KeyName
}
export interface AddSelfIssuedSessionParams {
    username: Username
    networkId: NetworkId
    origin: Origin
}
export interface GetSelfIssuedOnboardingParams {
    sessionId: SessionId
}
export interface CreateSelfIssuedWalletParams {
    sessionId: SessionId
    partyHint: PartyHint
    signingProviderId: SigningProviderId
}
export interface AllocateSelfIssuedWalletParams {
    sessionId: SessionId
    partyId: PartyId
}
export interface ConnectSelfIssuedSessionParams {
    sessionId: SessionId
    partyId: PartyId
}
export interface AllocatePartyForWalletParams {
    partyId: PartyId
}
export interface SetPrimaryWalletParams {
    partyId: PartyId
}
export interface RemoveWalletParams {
    partyId: PartyId
}
export interface ListWalletsParams {
    filter?: WalletFilter
}
export interface SignParams {
    transactionId: TransactionId
    partyId: PartyId
}
export interface SignMessageParams {
    messageId: MessageId
    partyId?: PartyId
}
export interface GetMessageToSignParams {
    messageId: MessageId
}
export interface DeleteMessageToSignParams {
    messageId: MessageId
}
export interface ExecuteParams {
    partyId: PartyId
    transactionId: TransactionId
}
export interface AddSessionParams {
    origin: Origin
    networkId: NetworkId
}
export interface GetTransactionParams {
    transactionId: TransactionId
}
export interface GetTransactionStatusParams {
    transactionId: TransactionId
    partyId?: PartyId
}
export interface ListTransactionsParams {
    limit?: Limit
    cursor?: Cursor
}
export interface DeleteTransactionParams {
    transactionId: TransactionId
}
export interface GenerateApiKeyParams {
    name: Name
}
export interface RemoveApiKeyParams {
    id: Id
}
export interface ListSigningProviderKeysParams {
    signingProviderId: SigningProviderId
}
export interface GetWalletParams {
    partyId: PartyId
}
export interface ChangeSigningProviderParams {
    signingProviderId: SigningProviderId
    partyId: PartyId
    publicKey: PublicKey
}
export interface ListNetworksResult {
    networks: Networks
}
export interface GetNetworkResult {
    network: Network
}
export interface SelfSignedAccessTokenResult {
    accessToken: AccessToken
}
export interface ListIdpsResult {
    idps: Idps
}
export interface CreateWalletResult {
    wallet: Wallet
}
export interface AddSelfIssuedSessionResult {
    sessionId: SessionId
}
export interface GetSelfIssuedOnboardingResult {
    userExists: UserExists
    wallets: Wallets
}
export interface CreateSelfIssuedWalletResult {
    wallet: Wallet
}
export interface AllocateSelfIssuedWalletResult {
    wallet: Wallet
}
export interface ConnectSelfIssuedSessionResult {
    wallet: Wallet
    accessToken: AccessToken
}
export interface AllocatePartyForWalletResult {
    wallet: Wallet
}
export interface RemovePartyResult {
    [key: string]: any
}
/**
 *
 * An array of wallets that match the filter criteria.
 *
 */
export type ListWalletsResult = Wallet[]
/**
 *
 * Added, updated  and disabled wallets as a result of the sync.
 *
 */
export interface SyncWalletsResult {
    added: SyncWalletsResultAdded
    updated: SyncWalletsResultUpdated
    disabled: SyncWalletsResultDisabled
}
export interface IsWalletSyncNeededResult {
    walletSyncNeeded: WalletSyncNeeded
}
export type SignResult =
    SignResultSigned | SignResultPending | SignResultRejected | SignResultFailed
export interface SignMessageResult {
    signature: Signature
    publicKey: PublicKey
}
export interface GetMessageToSignResult {
    message: MessageRaw
}
export interface ListMessagesToSignResult {
    messages: Messages
}
export interface ExecuteResult {
    [key: string]: any
}
/**
 *
 * Structure representing the connected network session
 *
 */
export interface AddSessionResult {
    id: Id
    origin?: Origin
    network: Network
    idp: Idp
    accessToken: AccessToken
    status: Status
    reason?: Reason
    rights: Rights
}
export interface ListSessionsResult {
    sessions: Sessions
}
export interface GetTransactionResult {
    id: TransactionId
    commandId: CommandId
    status: Status
    createdAt?: CreatedAt
    signedAt?: SignedAt
    preparedTransaction: PreparedTransaction
    preparedTransactionHash: PreparedTransactionHash
    payload?: Payload
    origin?: Origin
    externalTxId?: ExternalTxId
    failureReason?: FailureReason
}
export interface GetTransactionStatusResult {
    status: Status
    externalTxId?: ExternalTxId
    failureReason?: FailureReason
}
export interface ListTransactionsResult {
    transactions: Transactions
    nextCursor?: NextCursor
    count: Count
}
export interface GetUserResult {
    userId: UserIdentifier
    isAdmin: IsAdminFlag
}
export interface GeneratedApiKey {
    id: Id
    apiKey: ApiKeyResult
}
export interface ListApiKeysResult {
    apiKeys: ApiKeys
}
export interface ListSigningProviderKeysResult {
    keys: Keys
}
export type GetWalletResult = Wallet | Null
/**
 *
 * Generated! Represents an alias to any of the provided schemas
 *
 */

export type AddNetwork = (params: AddNetworkParams) => Promise<Null>
export type RemoveNetwork = (params: RemoveNetworkParams) => Promise<Null>
export type ListNetworks = () => Promise<ListNetworksResult>
export type GetNetwork = (params: GetNetworkParams) => Promise<GetNetworkResult>
export type SelfSignedAccessToken = (
    params: SelfSignedAccessTokenParams
) => Promise<SelfSignedAccessTokenResult>
export type AddIdp = (params: AddIdpParams) => Promise<Null>
export type RemoveIdp = (params: RemoveIdpParams) => Promise<Null>
export type ListIdps = () => Promise<ListIdpsResult>
export type CreateWallet = (
    params: CreateWalletParams
) => Promise<CreateWalletResult>
export type AddSelfIssuedSession = (
    params: AddSelfIssuedSessionParams
) => Promise<AddSelfIssuedSessionResult>
export type GetSelfIssuedOnboarding = (
    params: GetSelfIssuedOnboardingParams
) => Promise<GetSelfIssuedOnboardingResult>
export type CreateSelfIssuedWallet = (
    params: CreateSelfIssuedWalletParams
) => Promise<CreateSelfIssuedWalletResult>
export type AllocateSelfIssuedWallet = (
    params: AllocateSelfIssuedWalletParams
) => Promise<AllocateSelfIssuedWalletResult>
export type ConnectSelfIssuedSession = (
    params: ConnectSelfIssuedSessionParams
) => Promise<ConnectSelfIssuedSessionResult>
export type AllocatePartyForWallet = (
    params: AllocatePartyForWalletParams
) => Promise<AllocatePartyForWalletResult>
export type SetPrimaryWallet = (params: SetPrimaryWalletParams) => Promise<Null>
export type RemoveWallet = (
    params: RemoveWalletParams
) => Promise<RemovePartyResult>
export type ListWallets = (
    params: ListWalletsParams
) => Promise<ListWalletsResult>
export type SyncWallets = () => Promise<SyncWalletsResult>
export type IsWalletSyncNeeded = () => Promise<IsWalletSyncNeededResult>
export type Sign = (params: SignParams) => Promise<SignResult>
export type SignMessage = (
    params: SignMessageParams
) => Promise<SignMessageResult>
export type GetMessageToSign = (
    params: GetMessageToSignParams
) => Promise<GetMessageToSignResult>
export type ListMessagesToSign = () => Promise<ListMessagesToSignResult>
export type DeleteMessageToSign = (
    params: DeleteMessageToSignParams
) => Promise<Null>
export type Execute = (params: ExecuteParams) => Promise<ExecuteResult>
export type AddSession = (params: AddSessionParams) => Promise<AddSessionResult>
export type RemoveSession = () => Promise<Null>
export type ListSessions = () => Promise<ListSessionsResult>
export type GetTransaction = (
    params: GetTransactionParams
) => Promise<GetTransactionResult>
export type GetTransactionStatus = (
    params: GetTransactionStatusParams
) => Promise<GetTransactionStatusResult>
export type ListTransactions = (
    params: ListTransactionsParams
) => Promise<ListTransactionsResult>
export type DeleteTransaction = (
    params: DeleteTransactionParams
) => Promise<Null>
export type GetUser = () => Promise<GetUserResult>
export type GenerateApiKey = (
    params: GenerateApiKeyParams
) => Promise<GeneratedApiKey>
export type ListApiKeys = () => Promise<ListApiKeysResult>
export type RemoveApiKey = (params: RemoveApiKeyParams) => Promise<Null>
export type ListSigningProviderKeys = (
    params: ListSigningProviderKeysParams
) => Promise<ListSigningProviderKeysResult>
export type GetWallet = (params: GetWalletParams) => Promise<GetWalletResult>
export type ChangeSigningProvider = (
    params: ChangeSigningProviderParams
) => Promise<Null>
/* eslint-enable @typescript-eslint/no-unused-vars */

type Params<T> = T extends (...args: infer A) => any
    ? A extends []
        ? never
        : A[0]
    : never
type Result<T> = T extends (...args: any[]) => Promise<infer R> ? R : never

export type RpcTypes = {
    addNetwork: {
        params: Params<AddNetwork>
        result: Result<AddNetwork>
    }

    removeNetwork: {
        params: Params<RemoveNetwork>
        result: Result<RemoveNetwork>
    }

    listNetworks: {
        params: Params<ListNetworks>
        result: Result<ListNetworks>
    }

    getNetwork: {
        params: Params<GetNetwork>
        result: Result<GetNetwork>
    }

    selfSignedAccessToken: {
        params: Params<SelfSignedAccessToken>
        result: Result<SelfSignedAccessToken>
    }

    addIdp: {
        params: Params<AddIdp>
        result: Result<AddIdp>
    }

    removeIdp: {
        params: Params<RemoveIdp>
        result: Result<RemoveIdp>
    }

    listIdps: {
        params: Params<ListIdps>
        result: Result<ListIdps>
    }

    createWallet: {
        params: Params<CreateWallet>
        result: Result<CreateWallet>
    }

    addSelfIssuedSession: {
        params: Params<AddSelfIssuedSession>
        result: Result<AddSelfIssuedSession>
    }

    getSelfIssuedOnboarding: {
        params: Params<GetSelfIssuedOnboarding>
        result: Result<GetSelfIssuedOnboarding>
    }

    createSelfIssuedWallet: {
        params: Params<CreateSelfIssuedWallet>
        result: Result<CreateSelfIssuedWallet>
    }

    allocateSelfIssuedWallet: {
        params: Params<AllocateSelfIssuedWallet>
        result: Result<AllocateSelfIssuedWallet>
    }

    connectSelfIssuedSession: {
        params: Params<ConnectSelfIssuedSession>
        result: Result<ConnectSelfIssuedSession>
    }

    allocatePartyForWallet: {
        params: Params<AllocatePartyForWallet>
        result: Result<AllocatePartyForWallet>
    }

    setPrimaryWallet: {
        params: Params<SetPrimaryWallet>
        result: Result<SetPrimaryWallet>
    }

    removeWallet: {
        params: Params<RemoveWallet>
        result: Result<RemoveWallet>
    }

    listWallets: {
        params: Params<ListWallets>
        result: Result<ListWallets>
    }

    syncWallets: {
        params: Params<SyncWallets>
        result: Result<SyncWallets>
    }

    isWalletSyncNeeded: {
        params: Params<IsWalletSyncNeeded>
        result: Result<IsWalletSyncNeeded>
    }

    sign: {
        params: Params<Sign>
        result: Result<Sign>
    }

    signMessage: {
        params: Params<SignMessage>
        result: Result<SignMessage>
    }

    getMessageToSign: {
        params: Params<GetMessageToSign>
        result: Result<GetMessageToSign>
    }

    listMessagesToSign: {
        params: Params<ListMessagesToSign>
        result: Result<ListMessagesToSign>
    }

    deleteMessageToSign: {
        params: Params<DeleteMessageToSign>
        result: Result<DeleteMessageToSign>
    }

    execute: {
        params: Params<Execute>
        result: Result<Execute>
    }

    addSession: {
        params: Params<AddSession>
        result: Result<AddSession>
    }

    removeSession: {
        params: Params<RemoveSession>
        result: Result<RemoveSession>
    }

    listSessions: {
        params: Params<ListSessions>
        result: Result<ListSessions>
    }

    getTransaction: {
        params: Params<GetTransaction>
        result: Result<GetTransaction>
    }

    getTransactionStatus: {
        params: Params<GetTransactionStatus>
        result: Result<GetTransactionStatus>
    }

    listTransactions: {
        params: Params<ListTransactions>
        result: Result<ListTransactions>
    }

    deleteTransaction: {
        params: Params<DeleteTransaction>
        result: Result<DeleteTransaction>
    }

    getUser: {
        params: Params<GetUser>
        result: Result<GetUser>
    }

    generateApiKey: {
        params: Params<GenerateApiKey>
        result: Result<GenerateApiKey>
    }

    listApiKeys: {
        params: Params<ListApiKeys>
        result: Result<ListApiKeys>
    }

    removeApiKey: {
        params: Params<RemoveApiKey>
        result: Result<RemoveApiKey>
    }

    listSigningProviderKeys: {
        params: Params<ListSigningProviderKeys>
        result: Result<ListSigningProviderKeys>
    }

    getWallet: {
        params: Params<GetWallet>
        result: Result<GetWallet>
    }

    changeSigningProvider: {
        params: Params<ChangeSigningProvider>
        result: Result<ChangeSigningProvider>
    }
}

export class WalletJSONRPCUserAPI {
    public transport: RpcTransport

    constructor(transport: RpcTransport) {
        this.transport = transport
    }

    public async request<M extends keyof RpcTypes>(
        args: RequestArgs<RpcTypes, M>
    ): Promise<RpcTypes[M]['result']> {
        const response = await this.transport.submit(args as RequestPayload)

        if ('error' in response) {
            throw new Error(
                'RPC error: ' +
                    response.error.code +
                    ' - ' +
                    response.error.message
            )
        } else {
            return response.result as RpcTypes[M]['result']
        }
    }
}
export default WalletJSONRPCUserAPI
