name: Update Docs Snippets

on:
    workflow_dispatch:

    push:
        branches:
            - main
        paths:
            - docs/wallet-integration-guide/examples/snippets/**
            - docs/wallet-integration-guide/examples/scripts/**

jobs:
    update-snippets:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v7.0.0

            - name: Extract Snippet data
              run: node docs/scripts/generate-output-docs.mjs

            - name: Store Artifact output
              id: store-artifact
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              with:
                  name: splice-wallet-kernel-snippets
                  path: docs-output/

            - name: Prepare additional params
              id: additional-params
              run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

            - name: Update Main Docs Repo
              if: vars.ENABLE_SYNC_PROCESS == 'true'
              run: |
                  set -euo pipefail

                  curl -L --fail-with-body \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.MAIN_DOCS_REPO_TOKEN }}" \
                    -H "Content-Type: application/json" \
                    -H "User-Agent: ${{ github.repository }} update-docs-snippets workflow" \
                    -H "X-GitHub-Api-Version: 2026-03-10" \
                    -d @- \
                    "https://api.github.com/repos/${{ vars.MAIN_REPO_ORG }}/${{ vars.MAIN_REPO_NAME }}/dispatches" <<'JSON'
                  {
                    "event_type": "update_snippets",
                    "client_payload": {
                      "run-id": ${{ toJson(github.run_id) }},
                      "artifact-id": ${{ toJson(steps.store-artifact.outputs.artifact-id) }},
                      "repo-name": ${{ toJson(vars.SOURCE_REPO_NAME) }},
                      "repo-org": ${{ toJson(vars.SOURCE_REPO_ORG) }},
                      "repo-version": ${{ toJson(vars.SOURCE_REPO_VERSION) }},
                      "trigger_sha_short": ${{ toJson(steps.additional-params.outputs.short_sha) }}
                    }
                  }
                  JSON
